
Q.1 Create a NumPy 1D-array with 5 elements and perform basic operations


In [11]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

# a) Addition of 2 to all elements
print("After adding 2:", arr + 2)

# b) Multiply 3 with all elements
print("After multiplying by 3:", arr * 3)

# c) Divide every element by 2
print("After dividing by 2:", arr / 2)


After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


Q.2 Questions on Basic NumPy Array


In [12]:
# a) Reverse the NumPy array
arr = np.array([1, 2, 3, 6, 4, 5])
print("Original array:", arr)
print("Reversed array:", arr[::-1])


# b) Find the most frequent value and its indices

# i. Array x
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]
print("Array x:", x)
print("Most frequent value:", most_frequent)
print("Indices:", indices)


# ii. Array y
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)[0]
print("Array y:", y)
print("Most frequent value:", most_frequent)
print("Indices:",indices)

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]
Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: 1
Indices: [0 5 7 8 9]
Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value: 1
Indices: [0 1 2]


Q.3 Create a 2-D array and access elements using row and column indices


In [13]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# a) Access 1st row, 2nd column
print("1st row, 2nd column:", arr[0, 1])

# b) Access 3rd row, 1st column
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


Q.4 Create 1-D array named Zaira with 25 evenly spaced numbers from 10 to 100



In [14]:
Zaira = np.linspace(10, 100, 25)
print("Array Zaira:")
print(Zaira)

# Dimensions
print("Dimensions:", Zaira.ndim)

# Shape
print("Shape:", Zaira.shape)

# Total number of elements
print("Total elements:", Zaira.size)

# Data type
print("Data type:", Zaira.dtype)

# Total number of bytes
print("Total bytes:", Zaira.nbytes)

# Transpose using reshape()
transpose_Zaira = Zaira.reshape(1, 25)
print("Transpose using reshape():")
print(transpose_Zaira)

# Transpose using T attribute
print("Transpose using T:")
print(Zaira.T)

# Note:
# For a 1-D array, T does not change its shape.
# To get a 2-D transpose, reshape the array first.


Array Zaira:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape():
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q.5 Create a 2-D array with three rows and four columns



In [15]:
ucs420_Zaira = np.array([[10, 20, 30, 40],
                         [50, 60, 70, 80],
                         [90, 15, 20, 35]])

print("ucs420_Zaira:")
print(ucs420_Zaira)

# Mean
print("Mean:", np.mean(ucs420_Zaira))

# Median
print("Median:", np.median(ucs420_Zaira))

# Maximum
print("Maximum:", np.max(ucs420_Zaira))

# Minimum
print("Minimum:", np.min(ucs420_Zaira))

# Unique elements
print("Unique elements:", np.unique(ucs420_Zaira))

# Reshape to 4 rows and 3 columns
reshaped_ucs420_Zaira = ucs420_Zaira.reshape(4, 3)

print("Reshaped array:")
print(reshaped_ucs420_Zaira)

# Resize to 2 rows and 3 columns
resized_ucs420_Zaira = np.resize(ucs420_Zaira, (2, 3))

print("Resized array:")
print(resized_ucs420_Zaira)

ucs420_Zaira:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:
[[10 20 30]
 [40 50 60]]
