Q1. Sensor readings

In [2]:
import numpy as np
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a. Add 2°C to every reading using vectorization
corrected_temperature = temperature + 2
# b. Convert all temperatures from Celsius to Fahrenheit
fahrenheit = (9 / 5) * corrected_temperature + 32
# c. Identify all readings greater than 32°C using Boolean indexing
readings_greater_32 = corrected_temperature[corrected_temperature > 32]
# d. Count how many readings exceed 32°C
count = np.sum(corrected_temperature > 32)
# e. Vectorization and Boolean indexing make data processing efficient
# by operating on arrays directly without explicitly iterating through values.

Q2. Matrix representing daily steps

In [3]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# a) Total steps
total_steps = np.sum(steps)

# b) Mean steps
mean_steps = np.mean(steps)

# c) Maximum and minimum
maximum = np.max(steps)
minimum = np.min(steps)

# d) Total steps for each day
daily_total = np.sum(steps, axis=0)

# e) Total steps for each user
user_total = np.sum(steps, axis=1)

# f) Position of maximum value
max_position = np.unravel_index(
    np.argmax(steps), steps.shape
)

Q3. NumPy slicing, copying, reshaping and flattening

In [4]:
# a) Create original array
original = np.array([1, 2, 3, 4, 5, 6])

# b) Slice from index 1 to 4
subset = original[1:5]

# c) Modify subset
subset[0] = 999

print(original)
print(subset)

# d) Create a copy and modify it
copied = original[1:5].copy()

copied[0] = 500

print(original)
print(copied)

# e) Create 3 × 4 matrix
matrix = np.arange(1, 13).reshape(3, 4)

# f) Extract elements
first_row = matrix[0]
last_row = matrix[-1]
second_column = matrix[:, 1]
selected_elements = matrix[0:2, 1:3]

print(first_row)
print(last_row)
print(second_column)
print(selected_elements)

# g) flatten() and ravel()
flattened = matrix.flatten()
raveled = matrix.ravel()

print(flattened)
print(raveled)

# h) Modify ravel()
raveled[0] = 100

print(matrix)
print(raveled)

# i) Modify flatten()
flattened[1] = 200

print(matrix)
print(flattened)

# j) Shape, dimensions, size and dtype
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)
print(matrix.dtype)

[  1 999   3   4   5   6]
[999   3   4   5]
[  1 999   3   4   5   6]
[500   3   4   5]
[1 2 3 4]
[ 9 10 11 12]
[ 2  6 10]
[[2 3]
 [6 7]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[100   2   3   4   5   6   7   8   9  10  11  12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[  1 200   3   4   5   6   7   8   9  10  11  12]
(3, 4)
2
12
int64


Q4. Cognitive-assistive system

In [5]:
y = np.array([40, 65, 30, 85])

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

# a) Shape and dimensions
print(X.shape)
print(X.ndim)

# b) Transpose
XT = X.T
print(XT)

# c) Matrix product
XtX = X.T @ X
print(XtX)

# d) Matrix inverse
inverse = np.linalg.inv(XtX)
print(inverse)

# e) Ordinary Least Squares
beta = np.linalg.inv(X.T @ X) @ X.T @ y
print(beta)

# g) Predicted assistance score
new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta
print(predicted_score)

(4, 3)
2
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
[-0.15921454  0.14083853 10.06302242]
75.27862544779117
